[workspace]
authors = ["Filipe Fernandes <ocefpaf@gmail.com>"]
channels = ["conda-forge"]
name = "DarwinCore_quickCheck"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
pandas = ">=2.3.3,<3"
requests = ">=2.32.5,<3"
nbclassic = ">=1.3.3,<2"
